In [2]:
import numpy as np
import pandas as pd
import pandas_datareader.data as web

In [13]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [11]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [10]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [9]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [15]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [17]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [19]:
states = ['Texas', 'Utah', 'California']

In [20]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [23]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [24]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [25]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [26]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [29]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [30]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [32]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [33]:
obj['b']

1.0

In [34]:
obj[1]

1.0

In [35]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [37]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [38]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [39]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [40]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [42]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [43]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [45]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [46]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [47]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [48]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [50]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [51]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [52]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [53]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [54]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [55]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [56]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [57]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [58]:
data.iloc[1:3, 1]

Colorado    5
Utah        9
Name: two, dtype: int64

In [60]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [61]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [62]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [63]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [64]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [65]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [66]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [67]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [68]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [69]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [70]:
df1 = pd.DataFrame({'A' : [1, 2]})

In [71]:
df2 = pd.DataFrame({'B' : [3, 4]})

In [72]:
df1

A
0  1
1  2

In [73]:
df2

B
0  3
1  4

In [74]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [75]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [76]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [77]:
df2.loc[1, 'b'] = np.nan

In [78]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [79]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [80]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [81]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [82]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [83]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [84]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [85]:
arr = np.arange(12.).reshape((3, 4))

In [86]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [87]:
arr[0]

array([0., 1., 2., 3.])

In [88]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [91]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [92]:
series = frame.iloc[0]

In [93]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [95]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [96]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [97]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [98]:
series3 = frame['d']

In [99]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [100]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [101]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [102]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [103]:
frame

b         d         e
Utah    0.333081 -2.298547 -1.351923
Ohio    0.829773  0.559177  0.418448
Texas   0.214249 -0.257401 -0.539672
Oregon -1.505394  0.278151 -0.807801

In [104]:
np.abs(frame)

b         d         e
Utah    0.333081  2.298547  1.351923
Ohio    0.829773  0.559177  0.418448
Texas   0.214249  0.257401  0.539672
Oregon  1.505394  0.278151  0.807801

In [105]:
f = lambda x: x.max() - x.min()

In [106]:
frame.apply(f)

b    2.335167
d    2.857724
e    1.770371
dtype: float64

In [107]:
frame.apply(f, axis='columns')

Utah      2.631628
Ohio      0.411325
Texas     0.753921
Oregon    1.783546
dtype: float64

In [108]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [109]:
frame.apply(f)

b         d         e
min -1.505394 -2.298547 -1.351923
max  0.829773  0.559177  0.418448

In [110]:
format = lambda x: '%.2f' % x

In [112]:
frame.applymap(format)

b      d      e
Utah     0.33  -2.30  -1.35
Ohio     0.83   0.56   0.42
Texas    0.21  -0.26  -0.54
Oregon  -1.51   0.28  -0.81

In [113]:
frame['e'].map(format)

Utah      -1.35
Ohio       0.42
Texas     -0.54
Oregon    -0.81
Name: e, dtype: object

In [114]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [115]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [116]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [117]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [118]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [119]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [120]:
obj = pd.Series([4, 7, -3, 2])

In [121]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [122]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [123]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [124]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a' : [0, 1, 0, 1]})

In [125]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [126]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [127]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [128]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [129]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

rank() without any specifier computes the average of ranks for the entries concerned. This means that first, all entries are sorted in ascending order, then every duplicate value is counted and there ranks added up. The sum is then divided by the number of appearances for each value.
In the above example you would get an ascending order like this:

In [134]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

As you can see, the value 7 appears twice, at position 6 and 7, meaning the average is gonna be (6 + 7) / 2 = 6.5.
For 4 the average computes like this: (4 + 5) / 2 = 4.5

In [130]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

Here the positions in the sorted array are used directly, meaning that the first appearance of 7 at index 0 is gonna have a rank of 6.

You can also assign tie values the maximum value for the group, as well as sort them in descending order:

In [135]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

DataFrame can compute ranks over the rows or the columns

In [136]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a' : [0, 1, 0, 1],
                     'c' : [-2, 5, 8, -2.5]})

In [137]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [138]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [140]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [141]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [142]:
obj.index.is_unique

False

In [143]:
obj['a']

a    0
a    1
dtype: int64

In [144]:
obj['c']

4

In [146]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [147]:
df

0         1         2
a -0.282955 -0.972213 -1.547540
a -0.264452  0.683873  1.058132
b  2.795805  0.595978  0.115705
b  0.459068 -0.071576 -0.407950

In [148]:
df.loc['b']

0         1         2
b  2.795805  0.595978  0.115705
b  0.459068 -0.071576 -0.407950

In [154]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'],
                 columns=['one', 'two'])

In [150]:
df

one  two
a  1.40  NaN
b  7.10  4.5
c   NaN  NaN
d  0.75 -1.3

In [151]:
df.sum()

one    9.25
two    3.20
dtype: float64

In [152]:
df.sum(axis='columns')

a     1.40
b    11.60
c     0.00
d    -0.55
dtype: float64

In [155]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [156]:
df.idxmax()

one    b
two    d
dtype: object

idxmax or idxmin returns indirect statistics, meaning you get the idx where the max or min value are located respectively

In [1]:
df.cumsum()

NameError: name 'df' is not defined

Some methods are accumulations, like the cumsum above

In [158]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

Other methods are neither a reduction nor a accumulation. describe is one such example, that returns multiple statistics in one go

In [159]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [160]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

On non-numeric data, describe returns alternative summary statistics

In [3]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [4]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [5]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [6]:
returns = price.pct_change()

In [7]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-07-20  0.025974  0.014864  0.008339  0.014294
2021-07-21 -0.005132  0.009502  0.007447  0.011434
2021-07-22  0.009629 -0.004175  0.016844  0.005490
2021-07-23  0.011989  0.004477  0.012337  0.033657
2021-07-26  0.005519  0.007995 -0.008700  0.001959

In [8]:
returns['MSFT'].corr(returns['IBM'])

0.5174674090049252

In [9]:
returns['MSFT'].cov(returns['IBM'])

0.00014521047604550835

In [10]:
returns.MSFT.corr(returns.IBM)

0.5174674090049252

In [11]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.440944  0.734669  0.660961
IBM   0.440944  1.000000  0.517467  0.483758
MSFT  0.734669  0.517467  1.000000  0.775623
GOOG  0.660961  0.483758  0.775623  1.000000

In [12]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000362  0.000137  0.000240  0.000211
IBM   0.000137  0.000268  0.000145  0.000133
MSFT  0.000240  0.000145  0.000294  0.000224
GOOG  0.000211  0.000133  0.000224  0.000283

In [13]:
returns.corrwith(returns.IBM)

AAPL    0.440944
IBM     1.000000
MSFT    0.517467
GOOG    0.483758
dtype: float64

In [14]:
returns.corrwith(volume)

AAPL   -0.062908
IBM    -0.103126
MSFT   -0.055487
GOOG   -0.110806
dtype: float64

In [16]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [17]:
uniques = obj.unique()

In [18]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [19]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [20]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [21]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [22]:
mask = obj.isin(['b', 'c'])

In [23]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [24]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

Related to isin is the method Index.get_indexer, which gives you an index array from an array of possibly non-distinct values into another array of distinct values:

In [25]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [26]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [27]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [28]:
data = pd.DataFrame({'Qu1' : [1, 3, 4, 3, 4],
                    'Qu2' : [2, 3, 1, 2, 3],
                    'Qu3' : [1, 5, 2, 4, 4]})

In [29]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [30]:
result = data.apply(pd.value_counts).fillna(0)

In [31]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0